version: "3.9"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#  mysqldb:
#      image: mysql:latest
#      restart: unless-stopped
#      command: --default-authentication-plugin=mysql_native_password
#      environment:
#        - MYSQL_ROOT_PASSWORD=admin
#        - MYSQL_DATABASE=stack_overflow
#      volumes:
#        - db-backup:/var/lib/mysql
#  # core:
  #   build: core
  #   environment:
  #     - HOST=mysqldb
  #     - USER=root
  #     - DATABASE=stack_overflow
  #     - PASSWORD=admin
  #     - JWT_SECRET=stack_overflow_api
  #     - JWT_EXPIRES_IN=1
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mysqldb
  # ui:
  #   build: ui/
  #   environment:
  #     - BACKEND_SERVICE_NAME=core
  #     - BACKEND_SERVICE_PORT=5000
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - core
volumes:
  db-backup:
    external: true
